### ISSUE TITLE
Support for non-generic type parameter

### ISSUE THREAD

**Issue by spetz** [electricessence/Open.Serialization#1]
Hi,
At first, thank you for the library, that's what I've been struggling with recently and wanted to write the similar abstractions :).
What do you think about adding support for the methods that are non-generic (with type parameter), for example, when you implement `IInputFormatter` from ASP.NET Core, you need to pass `context.ModelType` to the `Deserialize` which is currently not possible. Newtonsoft support such methods, as well as UTF8JSON (with `NonGeneric` serializer).

**Comment by electricessence** [comment]
Hello!  Thanks for the inquiry...
I personally didn't immediately see the need... BUT I didn't dismiss it.

If you're suggesting completely separate overloads...

1. `Serialize<T>(T item)` ultimately that can take anything and return a string without issue.
2. `T Deserialize<T>(string value)` seems logical it would need T to get the type right.

I think the older style `object Deserialize(string item, Type type)` or something like that is obsolete?
I'm up for extending, but I'm struggling to find why this would be good, or if I should simply provide extensions that use the same methods but with <object> as the type.

**Comment by electricessence** [comment]
Ok I think I'm getting what you're putting down...
I'll mock something up...  Maybe you can comment.

**Comment by electricessence** [comment]
Would this do?
```cs
	public interface IDeserializeObject
	{
		object Deserialize(string value, Type type);
	}
```

**Comment by spetz** [comment]
Thank you for the response.
I think that `object Deserialize(string value, Type type)` will be sufficient.
The only usage I found was [here](https://github.com/snatch-dev/Convey/blob/master/src/Convey.WebApi/src/Convey.WebApi/Formatters/JsonInputFormatter.cs#L33), since `InputFormatterContext` contains `ModelType` property required for incoming request body deserialization.

**Comment by electricessence** [comment]
Ok.  I like.  I'll get something in and republish the packages. :)

**Comment by electricessence** [comment]
Ok so I published a new version of Open.Serialization but I'm struggling to see how to not obligate the downstream packages having to do more work to integrate.
Will update you as I go.

**Comment by spetz** [comment]
Thanks, waiting for the updates then!

**Comment by VictorBlomberg** [comment]
Hi,

I'd like to use this library, but I need non-generic support. Something like:

- `ValueTask SerializeAsync(Stream stream, Type type, object item, CancellationToken cancellationToken)`
- `ValueTask<object> DeserializeAsync(Stream stream, Type type, CancellationToken cancellationToken)`

This would allow to serialize and deserialize data of types not known at compile time, which is important in many scenarios -- libraries, dynamic scenarios and such.

I would be glad to help, create a PR or similar. Would you be open for this? Do you see any problems relating to this that need to be thought at/solved?

Thanks,

**Comment by electricessence** [comment]
Isn't this what you mean?
https://github.com/electricessence/Open.Serialization/blob/master/Open.Serialization/IDeserializeObjectAsync.cs

**Comment by electricessence** [comment]
But to proceed any further, things start to get a bit weird.
How do you end up using these?  You have to implement your own wrapper?

**Comment by electricessence** [comment]
@VictorBlomberg I'm looking into your request.  I'm going to see how this would work reverse engineering it for Newtonsoft.

**Comment by electricessence** [comment]
https://github.com/electricessence/Open.Serialization/commit/8d7390fbd545a46b8aa742516d9b251b9deb818b

**Comment by electricessence** [comment]
https://www.nuget.org/packages/Open.Serialization/1.5.0

**Comment by electricessence** [comment]
I have to continue down the package chain now to complete the integration.

**Comment by electricessence** [comment]
@VictorBlomberg @spetz 
I'm working on a new version 2.x that will expose all the methods you asking for with some elegant base class and default implementation options.  Hold tight.  I'll probably release today or at least this week.
Would definitely appreciate feedback and review.

**Comment by electricessence** [comment]
https://www.nuget.org/packages/Open.Serialization/2.0.0

**Comment by electricessence** [comment]
Please see the latest changes in master as they are a significant upgrade and include C#8 (.NET Standard 2.1) Interface Default Methods.

**Comment by electricessence** [comment]
Released: v2.1.0
If there are no objections, I'm going to close this issue as the requests have been fulfilled.
I will be extending the dependent libs (Netwtonsoft, STJ, and Utf8Json) to expose these features.

**Comment by electricessence** [comment]
All packages are updated in nuget.

**Comment by VictorBlomberg** [comment]
Hi! Sorry for my delayed response. This seems great!

Will take a closer look in the coming days. Thank you for your swift response.

**Comment by electricessence** [comment]
Well any feedback and help is appreciated.  This doesn't need to be some always growing monster.  It just needs to fit the specific demand, and for the few cases that has been brought up, it seemed like a no brainer to go ahead.  That said, it took a lot of thought to get right. :)

**Comment by electricessence** [comment]
One last update:  I migrated all "interface default implementations" to be extensions.
Collisions are avoided by only importing `Open.Serialization.Extensions` when needed by the consumer.
Feel free to review them as they should cover all fall back situations for the core interfaces.

**Comment by electricessence** [comment]
@spetz Now is a good time to update your project to all the latest packages.
Stable release, with all the bells and whistles.
